### ISSUE TITLE
Bug and Feature Request -- Loader hangs and blocks / No ability to deeply debug

### ISSUE THREAD

**Issue by sashafklein** [jalehman/port#132]
**Bug Description**
Upon opening my main Groups tab in Port, the loader next to Leap started spinning and hasn't stopped. I went to message someone in a group, and my message has hung, with a loader there as well. I'm not sure whether those are related, but it seems plausible.

Note: If I exit and re-enter the chat, my message then appears, but the top left loader continues to spin.

*Feature Request*: I'd love a better means of debugging issues and reporting bugs. Doesn't seem that I can Command+J to see any errors, or see an action log, or anything like that. And consequently, it doesn't seem easy to share reproduction steps or know myself what might have gone wrong. 

**To Reproduce**
1. Open Port => Groups
2. Open Group Chat
3. Message someone

**Expected Behavior**
It works, there are no loaders, and you don't have to switch panes to see your message.

More importantly:

- There's a prominent Debug button that gives relevant logs, and makes them easy to share -- either in an issue it opens on Github or some other service.
- It also gives the Port Version and any other Environment info upfront without the need to search.
Additionally, it'd be nice if I could "clear" any pending requests that are blocking, and sort of "restart my session" without closing and opening Port.

**Environment:**
 - OS: MacOS 
 - Version: 11.5.2
 - Port Version: 1.2.0

**Additional context**

I don't see the "little bug in the right hand corner" mentioned in this space in the template. Why not? That seems to see the problem, really.

**Comment by arthyn** [comment]
@sashafklein Hey there, the spinner and issues with messages were most likely from the big update and are not caused by Port. A fix for those went out today so you should see those resolved as soon as your urbit updates.

As far as the debugging tools, you can see quite a bit using the dev tools provided through the little bug icon or click view > toggle developer tools from the top bar menu. Sorry you aren't able to see the bug, maybe it's contrast isn't high enough. Let me know if you can't find it though, maybe that's an issue of it's own. You should also be able to see the version of Port using the top bar Help menu.

Can you expand more about what you mean by clearing requests and restarting your session?
