### ISSUE TITLE
Trying to boot a Comet

### ISSUE THREAD

**Issue by crites** [jalehman/port#159]
**Bug Description*
When trying to boot a Comet on my Windows 10 laptop I get the message 'Booting Comet Failed'.

**To Reproduce**
1. From main menu click 'Start without an ID.
2. Enter 'Comet1' in Name (local only) field
3. Click Continue

**Expected Behavior**
I expected a Comet to boot

**Screenshots**

**Environment:**
 - OS: Windows
 - Version: Windows 10 latest update
 - Port Version: v1.7.0

**Additional context**

If you still have it open, click the little bug in the right hand corner. You should see dev tools pop up in the main window, and also a background window with dev tools. Check either of the dev tools, click console and scroll to see if there's any errors, include those if possible.
![Boot Comet Failes](https://user-images.githubusercontent.com/547249/147231444-88066e67-a51a-4a24-aaa6-a5e6b9ab46e8.jpg)

**Comment by arthyn** [comment]
@crites hey there a fix was deployed for this in 1.7.1 let me know if you still experience it after updating.

**Comment by crites** [comment]
@arthyn I'm running 1.7.1 and I still can't boot a comet.  From the debug / background screen I see multiple messages Name localhost, Status (failed), Type xhr, Initiator xhr.js:177.....

**Comment by arthyn** [comment]
@crites can you maybe send some screenshots of the errors you're seeing in the console?

**Comment by crites** [comment]
@arthyn I have no idea why, but I was finally successful in booting a Comet.  I just opened Port (1.7.1) and the Comet and the groups I joined are still there.  How long is a comet supposed to last?

Also, I have two planets that Port (1.7.1) says are running on a VM (Ubuntu) on my TrueNAS system but I can not join any groups.  I think this may be due to me using the keys on more that one system. I now understand trying to boot a planet with the same keys on two systems is bad.  Can you give me any pointers on recovering these planets without having to spend the $$ to get new sets of keys?  I have tried cntl-D with no luck.

**Comment by arthyn** [comment]
@crites comets last indefinitely so likely it was there from before. May have gotten fixed from some stuff I did in 1.7.1. 

As far as the planets go, I guess my first question is are they two separate names? Or do you mean the same name/point was booted two separate times, in this case on different machines. 

If they are the same name, then it's considered the same planet because you used the same key twice. Because of that, everyone on the network has now heard from the same planet twice which basically breaks your communications. If this is the case, there's no way to get around it without spending ETH, you'll have to breach.

An urbit can only be run as a single instance, which is why Port allows you to import an already booted/existing ship. So let's say you booted the planet in Ubuntu VM and decided to move it to TrueNAS, then you'd just need to eject it on the original and import it into the new system, but the whole thing has to move over. It can't just be booted separately from the same key.

**Comment by crites** [comment]
@arthyn Yes, I have two planets with different name.  

So I deleted all the piers on my desktop computer, I also shutdown Port running in the VM of my server.  I then when to  www.bridge.urbit.org and generated a new key file for one of my planets.  When I try to boot my planet with the new key I get the following.

16:26:03 azimuth: loading snapshot with 291.850 events
16:26:08 address 00000241155c2cc8 out of loom!
loom: [0
16:26:08 000028000000000 : 0000028080000000)
Assertion '0' failed in noun/events.c:128
home: bailing out

**Comment by crites** [comment]
@arthyn Hi Hunter, I really appreciated your feedback but is there forum you could recommend on trying to get some help getting my Planet going.   I'm just looking for something a little closer to real time on getting responses.  I have posted to the Help channel in the Urbit community (from the Comet I booted), but the turn around on that is also kind of slow.

**Comment by arthyn** [comment]
@crites unfortunately these two avenues are really all we have. 

I believe what you may have run into here was not enough memory, currently we require a little too much on boot because of that 'azimuth loading snapshot' line. It drops down after the very first boot though.

**Comment by crites** [comment]
@arthyn you mean in my Desktop computer?  I'm running an i7 with 32GB of RAM.

After deleting the piers and trying again my planet booted so I'm all set.  The Help channel in the Urbit Community has proven to be very helpful.   I now have Visor running and am busy sniffing around.

Thanks again for all your help.
