### ISSUE TITLE
Cannot bootstrap comet on fresh install

### ISSUE THREAD

**Issue by felzix** [jalehman/port#202]
**Bug Description*

I'm just starting out so I'm following the Getting Started guide. I tried to make a comet. It fails to find the bootstrap pill even though the URL works when I enter it into a browser.

The error:
`18:58:22 failed to fetch https://bootstrap.urbit.org/urbit-v1.8.pill: Couldn't resolve host name`

Outputs to the terminal:
```
 ~ √ % port
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[2615:0514/185811.393335:ERROR:node_bindings.cc(276)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
checking 1
found socket 1
[2699:0514/185811.546539:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/port_Port.desktop"
```

**To Reproduce**
1. Install `port` via `snap`.
2. Run `port`
3. In the port UI, click "Start without an ID"
4. Enter a name
5. Click "Continue"
6. Wait ~5 seconds
7. See error

**Expected Behavior**
Process continues

**Environment:**
 - OS: Arch Linux
 - Version: 5.17.7-arch1-1
 - Port Version: v1.9.0

**Additional context**
I see that there's a version mismatch between port and the pill it's trying to download. Is there a better way to install `port` on arch than via snap?

**Comment by latter-bolden** [comment]
howdy @felzix 👋 

The urbit binaries are versioned independently from port, so that mismatch is expected.

Installing via snap is the recommended method, _but_ we do currently have a bug where snap is pointing to an unstable pre-release port version (1.9.0). This will be resolved soon, but for now, could you try installing the latest stable snap (1.8.0) locally and giving that a try? You can download it [here](https://github.com/urbit/port/releases/download/v1.8.0/port-1.8.0.snap).

That said, I'm not sure that will fix an issue related to host name resolution. It's strange that the urbit process is choking on the lookup when you can otherwise seemingly access it normally. I haven't personally run urbit or port on arch, but I have a manjaro box at the office I can try it on come Monday. In the meantime, the only other suggestion I'd have is to restart `systemd-resolved` or whatever service you're using for DNS.

**Comment by latter-bolden** [comment]
@felzix I was able to run the stable version fine in Manjaro. (note: you'll need to pass snap the `--dangerous` flag to install the package from the local file)

Let me know if you're still having trouble.
